name: Deploy to staging
on:
  push:
    branches:
      - "production"

jobs:
  redeploy_everything:
    name: Deploying everything to production cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server
        run: |
          echo "${{ secrets.SSH_KEY }}" &> ~/ssh_key.pem
          mkdir -p /home/runner/.ssh/
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 ~/ssh_key.pem
          ssh -i ~/ssh_key.pem azureuser@74.225.221.237 -t "cd deploy_turbo/ && git pull origin production && export PATH=/home/azureuser/.nvm/versions/node/v24.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm i -g pnpm && pnpm install && pnpm run build && pm2 restart all"
